# Keep the selected analog gain fixed; desktop sliders control software volume.
monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.platform-sound"
        alsa.card_name = "SC8280XP-HUAWEI-GAOKUN3"
      }
    ]
    actions = {
      update-props = { api.alsa.soft-mixer = true }
    }
  }
]
